from typing import Optional
from pydantic import BaseModel, EmailStr
from fastapi import APIRouter, Depends, Form, Request, status
from fastapi.responses import HTMLResponse, PlainTextResponse
from sqlalchemy.orm import Session

from database import get_db
import models

router = APIRouter(prefix="/api/leads", tags=["Lead Generation"])

class ColdEmailWebhookPayload(BaseModel):
    email: EmailStr
    first_name: Optional[str] = None
    company_name: Optional[str] = None
    lead_status: Optional[str] = "interested"

# Outbound Cold Email Webhook Listener (Instantly / Smartlead)
@router.post("/webhook", status_code=status.HTTP_200_OK)
async def cold_email_lead_webhook(
    payload: ColdEmailWebhookPayload,
    db: Session = Depends(get_db)
):
    normalized_email = payload.email.strip().lower()
    lead = models.LeadCapture(
        email=normalized_email,
        organization_name=payload.company_name or "Outbound Prospect",
        source_url="cold_email_campaign",
        lead_magnet_type="outbound_positive_reply"
    )
    db.add(lead)
    db.commit()
    return {"status": "lead_captured", "email": normalized_email}

# HTMX Lead Magnet Form Submission
@router.post("/capture", response_class=HTMLResponse)
async def capture_lead(
    request: Request,
    email: str = Form(...),
    org_name: str = Form(None),
    source_url: str = Form("/"),
    db: Session = Depends(get_db)
):
    normalized_email = email.strip().lower()
    lead = models.LeadCapture(
        email=normalized_email,
        organization_name=org_name.strip() if org_name else None,
        source_url=source_url,
        lead_magnet_type="statutory_dpdp_checklist_2026"
    )
    db.add(lead)
    db.commit()

    return HTMLResponse(
        content="""
        <div class="p-4 bg-emerald-50 border border-emerald-200 rounded-2xl text-center">
            <div class="text-emerald-700 font-bold text-sm mb-1">✓ Checklist & Notice Templates Ready!</div>
            <p class="text-xs text-emerald-600 mb-3">Download your compliance checklist directly below.</p>
            <a href="/api/leads/download-checklist" class="inline-block px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold rounded-xl transition-all shadow-sm">
                ⬇ Direct Download Checklist (.txt)
            </a>
        </div>
        """,
        status_code=status.HTTP_200_OK
    )

@router.get("/download-checklist")
async def download_statutory_checklist():
    content = """================================================================================
CONSENTLAYER | DPDP ACT 2023 STATUTORY COMPLIANCE CHECKLIST FOR CLINICS & LABS
================================================================================

1. SECTION 5(1) STATUTORY NOTICE REQUIREMENTS
   [ ] Multilingual Notice presented before collecting patient identification / phone numbers.
   [ ] Exact purpose specified: "Diagnostic testing and report delivery only".
   [ ] Name and contact email of Data Protection Officer (DPO) listed.
   [ ] Clear procedure on how patient can withdraw consent at any time.

2. SECTION 33 AUDIT TRAIL & LOG RETENTION
   [ ] Immutable time-stamped log of every staff access to patient records.
   [ ] WhatsApp report dispatch logs retained for audit verification.
   [ ] Session timeout enforced after 15 minutes of inactivity on LIMS software.

3. SECTION 8 DATA FIDUCIARY SECURITY SAFEGUARDS
   [ ] SHA-256 or bcrypt hashing on all clinic portal logins.
   [ ] WhatsApp Business API integration configured without cloud plain-text cache.
   [ ] Encrypted backups stored within Indian territorial boundary.

================================================================================
Generated by ConsentLayer DPDP Engine (https://consentlayers.in)
================================================================================
"""
    return PlainTextResponse(
        content=content,
        headers={
            "Content-Disposition": "attachment; filename=DPDP_Clinic_Compliance_Checklist_2026.txt"
        }
    )